feat(menu): removed MenuModal usage in favor of a responsive single HTML menu template
Roma-JS/roma-js-on-astro pull request #95
Opened 2024-10-21 22:15 UTC by pixu1980

feat(menu): removed MenuModal usage in favor of a responsive single HTML menu template

2024-10-22 16:43 UTC, FaberVitale requested changes

2024-10-22 16:53 UTC, pixu1980 commented on src/components/Navbar/Navbar.tsx
> +              isMenuVisible()
Thanks @FaberVitale you're definitely right!

I'm on it!

2024-10-22 17:23 UTC, pixu1980 commented on src/components/Navbar/Navbar.tsx
> +              isMenuVisible()
Solved in the last commit

2024-10-23 16:36 UTC, FaberVitale approved these changes

2024-10-23 16:37 UTC, merged